inherit_from: "configs/mono/replica/base_config.yaml"

Dataset:
  dataset_path: "datasets/replica"
  Calibration:
    fx: 600
    fy: 600
    cx: 599.5
    cy: 339.5
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1200
    height: 680
    depth_scale: 5000.0
    distorted: False